Disable shared libdexfile_support prebuilt.
This manual change is necessary to work around Soong problem where the
dropped source shared lib in https://r.android.com/1708390 causes a
failing dependency here:

  error: prebuilts/module_sdk/art/current/sdk/Android.bp:1293:1: reverse dependency "libdexfile_support" of "art-module-sdk_libdexfile_support@current" missing variant:
    os:android,image:,arch:x86_64_silvermont,sdk:
  available variants:
    /.../
    os:android,image:,arch:x86_64_silvermont (alias to os:android,image:,arch:x86_64_silvermont,sdk:,link:static)
    os:android,image:,arch:x86_64_silvermont,sdk: (alias to os:android,image:,arch:x86_64_silvermont,sdk:,link:static)
    os:android,image:,arch:x86_64_silvermont,sdk:,link:static
    /.../

The next prebuilt drop after that CL has been submitted will avoid that
dependency.

Cherry-picked from https://r.android.com/1708487.

Test: m nothing
Bug: 143978909
Change-Id: Idd19d7b879b8780831bc275df67bc0f2127c21ff
Merged-In: Idd19d7b879b8780831bc275df67bc0f2127c21ff